import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';

import { Header, Navbar, Results } from '../components';
import { IMovie } from '../types';
import requests from '../utils/requests';

const Home: NextPage<{ results: IMovie[] }> = ({ results }) => {
  return (
    <div>
      <Head>
        <title>Hulu</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <Navbar />
      <Results results={results} />
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const genre = context.query.genre;

  const request = await fetch(
    `https://api.themoviedb.org/3${
      // @ts-ignore
      requests[genre]?.url || requests.fetchTrending.url
    }`
  ).then((res) => res.json());
  return {
    props: {
      results: request.results,
    },
  };
};

export default Home;
